# 正直、docker-composeで他はTerminalやコマンドプロンプトで起動するのが一番開発しやすいです
# (以下のapi, appをコメントアウトしてdocker-compose up)

# - db, apiをdocker composeで起動
#   make db-be
# - dbのみを起動
#   docker compose up db

services:
  # db:
  #   image: mysql:8.0.32
  #   platform: linux/amd64 #mac環境で必須なことがあるらしい
  #   env_file: ./db/.env
  #   container_name: lol_custom_manager_db
  #   build:
  #     context: ./db
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     timeout: 5s
  #     retries: 10
  #   ports:
  #     - "3306:3306"
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api:
    build:
      context: ./backend/pubsub
    container_name: lol_custom_manager_api
    env_file: ./backend/pubsub/.env
    environment:
      - IS_DOCKER_COMPOSE=true
    stdin_open: true
    tty: true
    volumes:
      - ./backend/pubsub:/api/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  app:
    build:
      context: ./frontend
    container_name: lol_custom_manager_app
    env_file: ./frontend/.env
    environment:
      - IS_DOCKER_COMPOSE=true
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/myapp:/app/src
    ports:
      - "80:80"
